# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b60f74bb85554858347af46431335df7ec84a855d1fe5bcd172dfe25d22c02727f1e81bebe227ee16186ecb8cfbcd40fd4aa0fd88a5900ce0cfa0fb822e50920

test:
  secret_key_base: 95ce19cbf486c44ad5ee957a90203c827a964ac6587b22a0b664974d54cbe11ae1eeebe14e8376b533f7223dc6638b2c3985f810c92c9e29a52e64c5387793be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
